# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/nathon-wang"
  #weibo: "#"
  rss: "atom.xml"
  #zhihu: "#"
  #douban: "#"
  mail: "nathon.wang713@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "#"

rss: atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: "<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-64449977-1', 'auto');
      ga('send', 'pageview');

      </script>script>"

favicon: /favicon.ico

#你的头像url
avatar: /img/avatar.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: nathon-wang
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
# friends:
#   奥巴马的博客: http://localhost:4000/
#   卡卡的美丽传说: http://localhost:4000/
#   本泽马的博客: http://localhost:4000/
#   吉格斯的博客: http://localhost:4000/
#   习大大大不同: http://localhost:4000/
#   托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: Python, ArchLinux, Vim, Nodejs, Web, 科幻, 悬疑, 美剧, 游戏...
