theme: next
language: zh-Hans
author: nathon.wang
description: 编程、技术、生活、人生种种
title: 汪南的魔法卷
url: http://blog.nathon.wang
duoshuo_shortname: nathon-wang
deploy:
  type: git
  repo: git@github.com:nathon-wang/nathon-wang.github.io.git
  branch: master
